import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
const $=s=>document.querySelector(s);
const catalog=[{id:'heartsping',name:'爱心萌可',trait:'温柔的粉色伙伴',color:'#ff79b1'},{id:'kikiping',name:'淘气萌可',trait:'棒棒糖与小恶作剧',color:'#55d4e8'},{id:'gogoping',name:'勇气萌可',trait:'闪闪发亮的小星星',color:'#ffc340'},{id:'chachaping',name:'盼盼萌可',trait:'带来希望的四叶草',color:'#a2da51'},{id:'lalaping',name:'唱唱萌可',trait:'一起唱一首快乐的歌',color:'#c998f2'},{id:'yuanbaoping',name:'元宝萌可',trait:'带来好运的小元宝',color:'#f6c34d'}];
const canvas=$('#scene'),scene=new THREE.Scene();scene.background=new THREE.Color('#77bfd3');scene.fog=new THREE.Fog('#77bfd3',55,160);
let renderer;try{renderer=new THREE.WebGLRenderer({canvas,antialias:true});}catch(e){$('#start').textContent='浏览器不支持3D，请开启硬件加速';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
const camera=new THREE.PerspectiveCamera(43,1,.1,250);scene.add(new THREE.HemisphereLight('#fffaff','#61856d',2.8));const light=new THREE.DirectionalLight('#fff2d7',3);light.position.set(-10,20,10);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-15,right:15,top:22,bottom:-22,near:1,far:65});light.shadow.bias=-.0004;scene.add(light);scene.add(light.target);
const road=new THREE.Mesh(new THREE.BoxGeometry(15,.18,145),new THREE.MeshStandardMaterial({color:'#e3a3b2',roughness:.85}));road.position.set(0,-.1,62);road.receiveShadow=true;scene.add(road);
function box(w,h,d,x,y,z,color){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.8}));o.position.set(x,y,z);o.receiveShadow=true;scene.add(o);return o;}
box(150,.1,200,0,-.22,65,'#73bda1');for(let i=0;i<7;i++)box(.045,.012,143,(i-3)*2.25,.006,62,'#fff3ea');
for(let z=0;z<=120;z+=10){box(15,.014,.07,0,.016,z,'#fbe6eb');for(const sign of [-1,1]){box(.15,.75,.15,sign*7.9,.30,z,'#e8ffff');box(.08,.08,9.8,sign*7.9,.66,z+5,'#c5efeb');}}
for(let x=-7.5;x<7.5;x+=.5)for(let z=120;z<121;z+=.5)box(.5,.016,.5,x+.25,.018,z+.25,(Math.round(x*2)+Math.round(z*2))%2?'#163449':'#fff');
for(const x of [-7.4,7.4])box(.23,5.1,.23,x,2.5,120,'#f8f2e5');box(15,.65,.25,0,4.9,120,'#ff80b5');
const players=[],loader=new GLTFLoader();let loaded=0;let race={phase:'ready',elapsed:0,energy:100,boost:false,finishOrder:[],count:0},view=0,last=0;
function rig(c){c.joints=[];c.root.updateMatrixWorld(true);const meshes=[];c.model.traverse(o=>{if(o.isMesh)meshes.push(o);});const legs=meshes.filter(o=>/Short_leg/.test(o.name)),feet=meshes.filter(o=>/Little_foot|Little_rounded_foot|Foot/.test(o.name));
 for(const leg of legs){const b=new THREE.Box3().setFromObject(leg),center=b.getCenter(new THREE.Vector3()),pivot=new THREE.Group();c.root.add(pivot);pivot.position.copy(c.root.worldToLocal(new THREE.Vector3(center.x,b.max.y,center.z)));pivot.updateMatrixWorld(true);pivot.attach(leg);const foot=feet.filter(o=>Math.abs(new THREE.Box3().setFromObject(o).getCenter(new THREE.Vector3()).x-center.x)<.2)[0];if(foot)pivot.attach(foot);c.joints.push({pivot,side:center.x<c.root.position.x?-1:1,amp:.55});}
 for(const name of ['Left_small_arm','Right_small_arm','Left_arm','Right_arm','Right_raised_arm']){const arm=meshes.find(o=>o.name===name||o.name.startsWith(name+'_'));if(!arm)continue;const b=new THREE.Box3().setFromObject(arm),center=b.getCenter(new THREE.Vector3()),pivot=new THREE.Group();c.root.add(pivot);pivot.position.copy(c.root.worldToLocal(new THREE.Vector3(center.x,b.max.y,center.z)));pivot.updateMatrixWorld(true);pivot.attach(arm);if(name==='Right_small_arm'||name==='Right_raised_arm'){const paw=meshes.find(o=>o.name==='Right_small_paw'||o.name==='Greeting_paw');if(paw)pivot.attach(paw);}if(name==='Left_small_arm')meshes.filter(o=>o.name.startsWith('Handheld_treasure')).forEach(o=>pivot.attach(o));c.joints.push({pivot,side:center.x<c.root.position.x?1:-1,amp:.28});}}
await Promise.all(catalog.map(async(c,i)=>{const g=await loader.loadAsync(`models/${c.id}.glb`),model=g.scene;const b=new THREE.Box3().setFromObject(model),size=b.getSize(new THREE.Vector3()),center=b.getCenter(new THREE.Vector3()),scale=2.7/size.y;model.scale.setScalar(scale);model.position.set(-center.x*scale,-b.min.y*scale,-center.z*scale);const root=new THREE.Group();root.add(model);root.position.x=(i-(catalog.length-1)/2)*2.25;scene.add(root);model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});players[i]={root,model,distance:0,finished:null,gait:0};rig(players[i]);loaded++;$('#start').textContent=`萌可正在集合 ${loaded}/${catalog.length}`;})).catch(e=>{$('#start').textContent='加载失败，点击刷新';$('#start').disabled=false;$('#start').onclick=()=>location.reload();throw e;});
$('#start').disabled=false;$('#start').textContent='开始比赛';
function setBoost(value){if(!value)race.exhausted=false;race.boost=value&&race.phase==='racing';$('#boost').classList.toggle('held',race.boost);}
function startRace(){race={phase:'countdown',elapsed:0,energy:100,boost:false,finishOrder:[],count:3};for(const p of players){p.distance=0;p.finished=null;p.gait=0;p.root.position.z=0;p.root.position.y=0;p.joints.forEach(j=>j.pivot.rotation.x=0);}$('#panel').hidden=true;$('#boost').disabled=true;$('#countdown').textContent='3';}
$('#start').onclick=startRace;$('#boost').addEventListener('pointerdown',e=>{e.preventDefault();$('#boost').setPointerCapture(e.pointerId);setBoost(true);});for(const event of ['pointerup','pointercancel','lostpointercapture'])$('#boost').addEventListener(event,()=>setBoost(false));window.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat){e.preventDefault();if(race.phase==='ready'||race.phase==='finished')startRace();else setBoost(true);}});window.addEventListener('keyup',e=>{if(e.code==='Space')setBoost(false);});window.addEventListener('blur',()=>setBoost(false));document.addEventListener('visibilitychange',()=>{last=0;setBoost(false);});$('#view').onclick=()=>view=(view+1)%3;
function showResult(){race.phase='finished';setBoost(false);$('#boost').disabled=true;const rank=race.finishOrder.indexOf(0)+1;$('#panel').hidden=false;$('#panel .badge').textContent=rank===1?'冠军诞生！':'比赛完成';$('#panel h1').textContent=`爱心萌可获得第 ${rank} 名`;$('#panel p').textContent=`用时 ${players[0].finished.toFixed(2)} 秒。合理分配冲刺体力，再挑战一次！`;$('#start').textContent='再跑一场';}
function getState(){return {loaded,phase:race.phase,player:'heartsping',elapsed:+race.elapsed.toFixed(2),energy:Math.round(race.energy),boost:race.boost,finishOrder:race.finishOrder.map(i=>catalog[i].id),runners:players.map((p,i)=>({id:catalog[i].id,distance:+p.distance.toFixed(2),finished:p.finished,joints:p.joints.length}))};}
window.mengkeRace={getState};
function frame(now){requestAnimationFrame(frame);const dt=last?Math.min((now-last)/1000,.05):0;last=now;if(document.hidden)return;
 if(race.phase==='countdown'){race.count-=dt;$('#countdown').textContent=String(Math.max(1,Math.ceil(race.count)));if(race.count<=0){race.phase='racing';$('#countdown').textContent='出发！';setTimeout(()=>$('#countdown').textContent='',700);$('#boost').disabled=false;}}
 if(race.phase==='racing'){race.elapsed+=dt;const sprint=race.boost&&race.energy>0&&!race.exhausted;race.energy=THREE.MathUtils.clamp(race.energy+dt*(sprint?-26:17),0,100);if(sprint&&race.energy<=0)race.exhausted=true;const crossings=[];players.forEach((p,i)=>{if(p.finished!==null)return;const speed=i===0?(sprint?7.7:4.25):(4.9+i*.13+Math.sin(race.elapsed*.8+i*2)*.32);const old=p.distance;p.distance=Math.min(120,p.distance+speed*dt);p.gait+=dt*speed*2.6;if(p.distance>=120){p.finished=race.elapsed-dt+(120-old)/speed;crossings.push(i);}});crossings.sort((a,b)=>players[a].finished-players[b].finished).forEach(i=>race.finishOrder.push(i));if(race.finishOrder.length===catalog.length)showResult();}
 const order=players.map((p,i)=>i).sort((a,b)=>players[b].distance-players[a].distance||(players[a].finished??Infinity)-(players[b].finished??Infinity));$('#ranking').innerHTML=order.map(i=>`<li class="${i===0?'player':''}">${catalog[i].name}${i===0?' · 你':''}</li>`).join('');$('#rank').textContent=order.indexOf(0)+1;$('#distance').textContent=Math.floor(players[0].distance);$('#time').textContent=race.elapsed.toFixed(1);$('#energy').style.width=race.energy+'%';$('#energyValue').textContent=Math.round(race.energy)+'%';$('#boost').innerHTML=race.exhausted?'松开恢复体力':race.boost?'冲刺中！ <small>SPACE</small>':'按住加速 <small>SPACE</small>';
 players.forEach(p=>{p.root.position.z=p.distance;const running=race.phase==='racing'&&p.finished===null;p.root.position.y=running?.045*(1-Math.cos(p.gait*2)):0;p.root.rotation.z=running?Math.sin(p.gait)*.022:0;p.joints.forEach(j=>j.pivot.rotation.x=running?Math.sin(p.gait)*j.side*j.amp:0);});
 const lead=players[0].distance,w=canvas.clientWidth,narrow=w<700;const target=new THREE.Vector3(0,1.3,lead);const offsets=[new THREE.Vector3(narrow?0:7,narrow?10:7,narrow?26:19),new THREE.Vector3(0,7,-(narrow?28:20)),new THREE.Vector3(narrow?18:16,13,2)];camera.position.copy(target).add(offsets[view]);camera.lookAt(target);light.position.set(-10,20,lead+10);light.target.position.z=lead;renderer.render(scene,camera);}
new ResizeObserver(()=>{renderer.setSize(canvas.clientWidth,canvas.clientHeight,false);camera.aspect=canvas.clientWidth/canvas.clientHeight;camera.updateProjectionMatrix();}).observe(canvas);requestAnimationFrame(frame);

const context=document.modelContext;
if(context?.registerTool){const lifecycle=new AbortController();const register=t=>Promise.resolve(context.registerTool(t,{signal:lifecycle.signal})).catch(console.warn);
register({name:'get_race_state',description:'Read race progress, stamina and runner distances.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>getState()});
register({name:'start_mengke_race',description:'Start or restart the six-character race, controlling Heartsping.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{startRace();return getState();}});
register({name:'set_race_boost',description:'Hold or release the same sprint control as the visible boost button.',inputSchema:{type:'object',properties:{held:{type:'boolean'}},required:['held'],additionalProperties:false},execute:input=>{if(typeof input.held!=='boolean')throw new Error('held must be boolean');setBoost(input.held);return getState();}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
