import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
const $=s=>document.querySelector(s);
const catalog=[{id:'heartsping',name:'爱心萌可',trait:'温柔的粉色伙伴',color:'#ff79b1'},{id:'kikiping',name:'淘气萌可',trait:'棒棒糖与小恶作剧',color:'#55d4e8'},{id:'gogoping',name:'勇气萌可',trait:'闪闪发亮的小星星',color:'#ffc340'},{id:'chachaping',name:'盼盼萌可',trait:'带来希望的四叶草',color:'#a2da51'},{id:'lalaping',name:'唱唱萌可',trait:'一起唱一首快乐的歌',color:'#c998f2'},{id:'yuanbaoping',name:'元宝萌可',trait:'带来好运的小元宝',color:'#f6c34d'}];
const canvas=$('#scene'),viewport=$('#viewport');
let renderer;
try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});}catch(e){$('#loading').innerHTML='<strong>浏览器暂时无法显示 3D</strong><span>请开启硬件加速，或换一个支持 WebGL 的浏览器。</span>';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;
const scene=new THREE.Scene();scene.fog=new THREE.Fog('#214b5d',28,65);
const camera=new THREE.PerspectiveCamera(38,1,.1,100);camera.position.set(0,4.2,16);
const controls=new OrbitControls(camera,canvas);controls.target.set(0,1.5,0);controls.enableDamping=true;controls.dampingFactor=.08;controls.minDistance=3;controls.maxDistance=26;controls.maxPolarAngle=Math.PI*.94;controls.enablePan=true;controls.autoRotateSpeed=.6;
scene.add(new THREE.HemisphereLight('#eaf8ff','#819aad',2.8));const key=new THREE.DirectionalLight('#fff2e3',3.5);key.position.set(-5,9,8);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-9,right:9,top:7,bottom:-7,near:.1,far:30});key.shadow.bias=-.0003;scene.add(key);const rim=new THREE.DirectionalLight('#73e9ea',2);rim.position.set(5,6,-5);scene.add(rim);
const stage=new THREE.Mesh(new THREE.CylinderGeometry(8.5,8.65,.28,96),new THREE.MeshStandardMaterial({color:'#b9d8e0',roughness:.8}));stage.position.y=-.14;stage.receiveShadow=true;scene.add(stage);
const rimRing=new THREE.Mesh(new THREE.TorusGeometry(8.42,.032,8,128),new THREE.MeshBasicMaterial({color:'#7cf3d6'}));rimRing.rotation.x=-Math.PI/2;rimRing.position.y=.014;scene.add(rimRing);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:'#244d5d',roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.3;floor.receiveShadow=true;scene.add(floor);
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),characters=[],pickMeshes=[];let selected=-1,loaded=0,dancing=false,move=null,toastTimer;
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),1800);}
function go(position,target){move={from:camera.position.clone(),to:position.clone(),startTarget:controls.target.clone(),target:target.clone(),start:performance.now()};}
function focus(i){if(!characters[i])return;selected=i;document.querySelectorAll('#roster button').forEach((b,j)=>{b.classList.toggle('selected',j===i);b.setAttribute('aria-pressed',String(j===i));});const p=characters[i].root.position;go(new THREE.Vector3(p.x,2.7,p.z+6),new THREE.Vector3(p.x,1.5,p.z));}
function view(name){const t=selected>=0?new THREE.Vector3(characters[selected].root.position.x,1.5,characters[selected].root.position.z):new THREE.Vector3(0,1.5,0);const d=selected>=0?6:16;const offsets={front:[0,d*.21,d],left:[-d,d*.21,0],right:[d,d*.21,0],back:[0,d*.21,-d],top:[0,d,.01]};go(t.clone().add(new THREE.Vector3(...offsets[name])),t);document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));}
function reset(){selected=-1;document.querySelectorAll('#roster button').forEach(b=>{b.classList.remove('selected');b.setAttribute('aria-pressed','false');});view('front');}
for(const [i,c]of catalog.entries()){const b=document.createElement('button');b.style.setProperty('--color',c.color);b.setAttribute('aria-pressed','false');b.disabled=true;b.innerHTML=`<span class="dot"></span><span><span class="char-name">${c.name}</span><span class="char-trait">${c.trait}</span></span>`;b.onclick=()=>{focus(i);hop(i);};$('#roster').append(b);}
const loader=new GLTFLoader();
await Promise.all(catalog.map(async(c,i)=>{try{const gltf=await loader.loadAsync(`${document.body.dataset.models||'models/'}${c.id}.glb`);const model=gltf.scene;const box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());const scale=3.1/size.y;model.scale.setScalar(scale);model.position.set(-center.x*scale,-box.min.y*scale,-center.z*scale);const root=new THREE.Group();root.add(model);root.position.set((i-(catalog.length-1)/2)*2.35,0,Math.abs(i-(catalog.length-1)/2)*-.16);scene.add(root);model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.userData.characterIndex=i;pickMeshes.push(o);}});const ring=new THREE.Mesh(new THREE.TorusGeometry(.72,.023,8,64),new THREE.MeshBasicMaterial({color:c.color,transparent:true,opacity:.45}));ring.rotation.x=-Math.PI/2;ring.position.set(root.position.x,.025,root.position.z);scene.add(ring);characters[i]={root,model,ring,base:root.position.clone(),jump:-1};$('#roster').children[i].disabled=false;loaded++;$('#loadCount').textContent=`${loaded} / ${catalog.length}`;}catch(e){console.error(e);throw new Error(`${c.name}加载失败`);}})).catch(e=>{$('#loading').innerHTML=`<strong>${e.message}</strong><button onclick="location.reload()">重新加载</button>`;throw e;});
$('#loading').classList.add('hidden');$('#play').disabled=false;
function hop(i){characters[i].jump=performance.now();}
$('#auto').onclick=()=>{controls.autoRotate=!controls.autoRotate;$('#auto').setAttribute('aria-pressed',String(controls.autoRotate));};$('#dance').onclick=()=>{dancing=!dancing;$('#dance').setAttribute('aria-pressed',String(dancing));};$('#fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen?.().catch(()=>toast('此浏览器暂不支持全屏'));};$('#reset').onclick=reset;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));
let down;canvas.addEventListener('pointerdown',e=>down={x:e.clientX,y:e.clientY,time:performance.now()});canvas.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>7||performance.now()-down.time>600)return;const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects(pickMeshes,false);if(hits.length)greet(hits[0].object.userData.characterIndex);});controls.addEventListener('start',()=>move=null);
let game={active:false,queue:[],score:0,started:0,elapsed:0};
function startGame(){game={active:true,queue:catalog.map((_,i)=>i).sort(()=>Math.random()-.5),score:0,started:performance.now(),elapsed:0};controls.autoRotate=false;$('#auto').setAttribute('aria-pressed','false');dancing=false;$('#dance').setAttribute('aria-pressed','false');$('#gameStats').hidden=false;$('#score').textContent='0';$('#play').textContent='重新开始';reset();updateMission();}
function updateMission(){const target=catalog[game.queue[game.score]];$('#mission').textContent=`第 ${game.score+1} 关：请点击「${target.name}」`;}
function greet(i){hop(i);if(!game.active){toast(`${catalog[i].name}：你好呀！`);return;}
 if(i!==game.queue[game.score]){toast(`这是${catalog[i].name}，再找找！`);return;}
 game.score++;$('#score').textContent=String(game.score);if(game.score===catalog.length){game.elapsed=Math.round((performance.now()-game.started)/1000);game.active=false;$('#mission').textContent=`全部找到啦！用时 ${game.elapsed} 秒。`;$('#play').textContent='再玩一次';toast('六个好朋友都找到啦！');characters.forEach((_,j)=>hop(j));}else{toast('找对啦！下一位是谁？');updateMission();}}
$('#play').onclick=startGame;
canvas.addEventListener('keydown',e=>{if(e.key==='Home'){reset();e.preventDefault();}if(e.key==='ArrowLeft'||e.key==='ArrowRight'){focus((selected+(e.key==='ArrowLeft'?-1:1)+catalog.length)%catalog.length);e.preventDefault();}if(e.key==='Enter'&&selected>=0)greet(selected);});
function resize(){const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();if(w<600&&selected<0)camera.position.set(0,7,28);}
new ResizeObserver(resize).observe(viewport);resize();
function frame(now){requestAnimationFrame(frame);if(move){const p=Math.min((now-move.start)/700,1),e=p*p*(3-2*p);camera.position.lerpVectors(move.from,move.to,e);controls.target.lerpVectors(move.startTarget,move.target,e);if(p===1)move=null;}for(let i=0;i<characters.length;i++){const c=characters[i],t=(now-c.jump)/1000;const jump=t>=0&&t<.8?Math.sin(t/.8*Math.PI)*.65:0;c.root.position.y=jump+(dancing?Math.max(0,Math.sin(now*.006+i))*.24:0);c.root.rotation.y=dancing?Math.sin(now*.002+i)*.24:0;c.ring.material.opacity=selected===i?.9:.4;}if(game.active)$('#time').textContent=String(Math.round((now-game.started)/1000));controls.update();renderer.render(scene,camera);}requestAnimationFrame(frame);
function getState(){return {loaded,selected:selected<0?null:catalog[selected].name,dancing,autoRotate:controls.autoRotate,camera:camera.position.toArray(),game:{active:game.active,score:game.score,target:game.active?catalog[game.queue[game.score]].id:null},characters:catalog.map(c=>({id:c.id,name:c.name}))};}
window.mengke={getState,focus,view,reset};
const api=document.modelContext;
if(api?.registerTool){const lifecycle=new AbortController();const register=t=>Promise.resolve(api.registerTool(t,{signal:lifecycle.signal})).catch(console.warn);
 register({name:'get_playground_state',description:'Read loaded characters, selected character, view and game progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>getState()});
 register({name:'set_playground_view',description:'Choose a character close-up or all six friends, then set a viewing angle.',inputSchema:{type:'object',properties:{character:{type:'string',enum:['all',...catalog.map(c=>c.id)]},angle:{type:'string',enum:['front','left','right','back','top']}},required:['character','angle'],additionalProperties:false},execute:input=>{const i=catalog.findIndex(c=>c.id===input.character);if(input.character!=='all'&&i<0)throw new Error('Unknown character');if(!['front','left','right','back','top'].includes(input.angle))throw new Error('Unknown angle');if(input.character==='all')reset();else focus(i);view(input.angle);return {selected:input.character,angle:input.angle};}});
 register({name:'start_find_friends_game',description:'Start or restart the visible six-round find-a-character game.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{startGame();return getState();}});
 register({name:'greet_playground_character',description:'Click a character to make it jump; during the game this submits that character as the answer.',inputSchema:{type:'object',properties:{character:{type:'string',enum:catalog.map(c=>c.id)}},required:['character'],additionalProperties:false},execute:input=>{const i=catalog.findIndex(c=>c.id===input.character);if(i<0)throw new Error('Unknown character');greet(i);return getState();}});
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}

